SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE User;
TRUNCATE TABLE Bookmark;
TRUNCATE TABLE Comment;
TRUNCATE TABLE Follow;
TRUNCATE TABLE Image;
TRUNCATE TABLE Likes;
SET REFERENTIAL_INTEGRITY TRUE;